happydog/urls.py
"""happydog URL Configuration
"""
from django.conf.urls import url
from django.contrib import admin
from happy import views

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^index', views.index, name='main'),
    url(r'^customers$', views.customers, name='customers'),
    url(r'^get_appointments$', views.get_appointments),
    url(r'^get_pets$', views.get_pets),
    url(r'^get_pet$', views.get_pet),
    url(r'^create_appointment$', views.create_appointment),
    url(r'^delete_appointment$', views.delete_appointment),
    url(r'^update_appointment$', views.update_appointment),
    url(r'^pay_appointment', views.pay_appointment),
    url(r'^create_appointment_new_pet_owner', views.create_appointment_new_pet_owner),
    url(r'^create_pet', views.create_pet),
    url(r'^update_pet', views.update_pet),
    url(r'^get_breeds', views.get_breeds),
    url(r'^get_hairs', views.get_hair_types),
    url(r'^get_sizes', views.get_sizes),
]

happy/models.py
import datetime

from django.db import models


def get_picture_upload_path(picture, filename):
        return "{}/{}".format(picture.pet.id, filename)


# We have to ensure that we will always create the pet before upload any image!!!
def get_upload_path(pet, filename):
    return "{}/{}".format(pet.id, filename)


class Customer(models.Model):
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=256, unique=True)
    cellphone = models.IntegerField(unique=True)
    landphone = models.IntegerField(null=True, blank=True, unique=True)
    club_happy = models.BooleanField(default=False)
    # Add function to get next free appointment
    # This should be checked when giving the appointment?

    def __unicode__(self):
        return self.name


class PetBreed(models.Model):
    name = models.CharField(max_length=256, unique=True)

    def __unicode__(self):
        return self.name


class Pet(models.Model):


    HAIR_TYPES = (
        ('short', 'Corto'),
        ('medium', 'Medio'),
        ('long', 'Largo')
    )
    PET_SIZES = (
        ('small', 'Pequeno'),
        ('medium', 'Mediano'),
        ('big', 'Grande')
    )
    name = models.CharField(max_length=256)
    owners = models.ManyToManyField(Customer)
    breed = models.ForeignKey(PetBreed, null=True, blank=True)
    hair_type = models.CharField(max_length=100, choices=HAIR_TYPES, null=True, blank=True)
    size = models.CharField(max_length=30, choices=PET_SIZES, null=True, blank=True)
    annotations = models.CharField(max_length=2048, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    birthday_week = models.IntegerField(null=True, blank=True)
    thumbnail = models.ImageField(upload_to=get_upload_path, null=True, blank=True)

    @property
    def long_name(self):
        str_name = self.name
        for o in self.owners.all():
            str_name += " - ".format(o.name)
        return str_name

    def __unicode__(self):
        str = self.name
        for o in self.owners.all():
            str += " - ({})".format(o.name)
        return str

    def save(self, *args, **kwargs):
        if self.birthday is not None and self.birthday != '':
            if type(self.birthday) is unicode or type(self.birthday) is str:
                d = datetime.datetime.strptime(self.birthday, "%d/%m/%Y").date()
                week = d.isocalendar()[1]
                self.birthday = d
            else:
                week =  self.birthday.isocalendar()[1]
            self.birthday_week = week
        super(Pet, self).save(*args, **kwargs)


class PetPictures(models.Model):
    customer = models.ForeignKey(Customer)
    picture = models.ImageField(upload_to=get_upload_path)
    description = models.CharField(max_length=2048)
    pet = models.ForeignKey(Pet, on_delete=models.DO_NOTHING)

    def __unicode__(self):
        return self.description


class Service(models.Model):
    name = models.CharField(max_length=128)
    price = models.IntegerField()

    def __unicode__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    brand = models.CharField(max_length=255)
    cost = models.FloatField()
    price = models.FloatField()

    def __unicode__(self):
        return "{} - {}".format(self.name + self.brand)


class Appointment(models.Model):
    pet = models.ForeignKey(Pet)
    services = models.ManyToManyField(Service)
    start = models.DateTimeField()
    end = models.DateTimeField()
    notes = models.CharField(max_length=2048)
    paid = models.BooleanField(default=False)
    amount_paid = models.FloatField(default=0)

    def __unicode__(self):
        return "{} ({} - {})".format(self.pet, self.start, self.end)

happy/forms.py
from django import forms

class PetForm(forms.form):
    name = forms.CharField(label='Nombre del Peludo')

happy/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse, HttpResponseNotFound
from models import Customer, Pet, Appointment, Service, PetBreed
from django.db.models import Q
from datetime import datetime
from django.db import IntegrityError


def index(request):
    context = {
        'services': Service.objects.all().order_by('name')
    }
    return render(request, 'happy/main.html', context)


def customers(request):
    customers_list = Customer.objects.select_related().order_by('name')
    breed_list = PetBreed.objects.all().order_by('name')
    context = {
        'customers': customers_list,
        'breeds': breed_list,
        'hair_types': Pet.HAIR_TYPES,
        'pet_sizes': Pet.PET_SIZES
    }
    return render(request, 'happy/customers.html', context)


def get_appointments(request):
    start = request.GET.get('start', '')
    end = request.GET.get('end', '')
    # TODO: Implement a serializer
    appointments = Appointment.objects.filter(start__range=[start, end])
    apps = []
    for app in appointments:
        a = {}
        a['id'] = app.pk
        a['type'] = 'appointment'
        a['title'] = app.pet.name
        a['start'] = app.start
        a['end'] = app.end
        a['description'] = app.notes
        a['pet_id'] = app.pet.pk
        a['pet_long_name'] = app.pet.long_name
        a['services'] = []
        a['paid'] = app.paid
        a['amount_paid'] = app.amount_paid
        # If its an old appointment and it was not paid, show it in red
        if app.end < datetime.now() and not app.paid:
            a['color'] = '#B40404'
        # If its an old appointment and it was paid, show it in green
        elif app.paid:
            a['color'] = '#298A08'
        for s in app.services.all():
            a['services'].append({'id': s.id, 'name': s.name, 'price': s.price})
        apps.append(a)
    start = datetime.strptime(start, '%Y-%m-%d').date()
    birthday_pets = Pet.objects.filter(birthday_week=start.isocalendar()[1])
    bdays = {}
    for pet in birthday_pets:
        day = str(datetime.now().year) + pet.birthday.strftime('-%m-%d')
        p = {}
        p['years'] = datetime.now().year - pet.birthday.year
        p['name'] = pet.name
        p['id'] = pet.id
        if day in bdays:
            bdays[day]['pets'].append(p)
            # Only add first 3 pets in the allday event title
            if len(bdays[day]['pets']) <= 2:
                bdays[day]['title'] += '\n' + pet.name
            elif len(bdays[day]['pets']) == 3:
                bdays[day]['title'] += '\n ...'
        else:
            bdays[day] = {}
            bdays[day]['start'] = day
            bdays[day]['end'] = day
            bdays[day]['pets'] = []
            bdays[day]['pets'].append(p)
            bdays[day]['type'] = 'birthday'
            bdays[day]['title'] = pet.name
    for b, app in bdays.iteritems():
        apps.append(app)
    return JsonResponse(apps, safe=False)


def get_pets(request):
    type = request.GET.get('type', 'main')
    limit = request.GET.get('limit', 15)
    q = request.GET.get('query')
    if q is not None:
        pets = Pet.objects.filter(
            Q(name__contains=q) |
            Q(owners__name__contains=q) |
            Q(owners__cellphone__contains=q) |
            Q(owners__email__contains=q)
        ).order_by('name').distinct()[:limit]
        context = {
            'pets': pets
        }
    else:
        return HttpResponseNotFound('Unknown Search Type')
    # TODO: Serialize the returning objects
    # TODO: Return the same serialized objects always and let JS (typeahead+handlebars) to do the magic
    if type == 'main':
        return render(request, 'happy/pets_search_result.html', context)
    elif type == 'appointment':
        l = []
        for p in pets:
            for a in p.appointment_set.all():
                print(a)
            l.append({
                'pet_long_name': p.long_name,
                'pet_name': p.name,
                'pet_id': p.id,
                'pet_birthday': p.birthday.strftime('%d/%m/%Y'),
                'pet_breed': p.breed.name,
                'pet_description': p.annotations,
                'owner_name': p.owners.first().name,
                'owner_id': p.owners.first().id,
                'owner_phone': p.owners.first().cellphone,
                'owner_email': p.owners.first().email,
                'owner_club_happy': p.owners.first().club_happy
            })
        return JsonResponse(l, safe=False)
    else:
        return HttpResponseNotFound('Unknown Search Type')


def get_pet(request):
    pet_pk = request.GET.get('pet_pk')
    if pet_pk is not None:
        pet = Pet.objects.get(pk=pet_pk)
        owners = pet.owners.all()
        pets = Pet.objects.filter(
            Q(owners__in=owners)
        ).distinct()
        appointments = Appointment.objects.filter(
            Q(pet__in=pets)
        ).order_by('-start')
        context = {
            'selected_pet_pk': pet.pk,
            'pets': pets,
            'owners': owners,
            'last_appointments': appointments
        }
        return render(request, 'happy/pet_info.html', context)
    return HttpResponseNotFound()


def get_phones(request):
    limit = request.GET.get('limit', 15)
    q = request.GET.get('q')
    if q is not None:
        pets = Pet.objects.filter(
            Q(owners__cellphone__contains=q) |
            Q(owners__landphone__contains=q)
        ).order_by('name').distinct()[:limit]
        context = {
            'pets': pets
        }
        return render(request, 'happy/phone_search_result.html', context)
    return HttpResponse('Nothing to search')


def create_appointment(request):
    try:
        pet = Pet.objects.get(id=request.GET.get('pet_pk'))
        start = request.GET.get('start')
        end = request.GET.get('end')
        services_list = request.GET.get('services')
        app = Appointment()
        app.pet = pet
        app.start = start
        app.end = end
        app.save()
        if services_list is not None and services_list != '':
            services_list = services_list.split(',')
            services = Service.objects.filter(id__in=services_list)
            app.services = services
            app.save()
        return JsonResponse({'pet_id': pet.id})
    except Exception as e:
        return HttpResponse(e.message, status=500)


def delete_appointment(request):
    try:
        appointment = Appointment.objects.get(id=request.GET.get('app_pk'))
        appointment.delete()
        return HttpResponse('Deleted')
    except Exception as e:
        return HttpResponse(e.message, status=500)


def update_appointment(request):
    try:
        appointment = Appointment.objects.get(id=request.GET.get('app_pk'))
        services_list = request.GET.get('service_pks').split(',')
        services = Service.objects.filter(id__in=(services_list))
        appointment.services = services
        appointment.save()
        return HttpResponse('Updated')
    except Exception as e:
        return HttpResponse(e.message, status=500)


def pay_appointment(request):
    try:
        appointment = Appointment.objects.get(id=request.GET.get('app_pk'))
        appointment.paid = True
        appointment.amount_paid = request.GET.get('total_paid')
        appointment.save()
        return HttpResponse('Paid')
    except Exception as e:
        return HttpResponse(e.message, status=500)


def create_appointment_new_pet_owner(request):
    try:
        owner_id = request.GET.get('owner_id', False)
        owner_email = request.GET.get('owner_email')
        owner_phone = request.GET.get('owner_phone')
        if owner_id:
            owner = Customer.objects.get(id=owner_id)
        else:
            owner = Customer()
        owner.name = request.GET.get('owner_name')
        owner.email = owner_email
        owner.cellphone = owner_phone
        owner.club_happy = request.GET.get('owner_club_happy')
        owner.save()

        pet_id = request.GET.get('pet_id', False)
        if pet_id:
            pet = Pet.objects.get(id=pet_id)
        else:
            pet = Pet()
        pet.name = request.GET.get('pet_name')
        pet.breed = request.GET.get('pet_breed', None)
        pet.birthday = request.GET.get('pet_bday', None)
        pet.annotations = request.GET.get('pet_desc', None)
        pet.save()
        pet.owners.add(owner)
        pet.save()
        start = request.GET.get('start_date')
        end = request.GET.get('end_date')
        services_list = request.GET.get('services')
        app = Appointment()
        app.pet = pet
        app.start = start
        app.end = end
        app.save()
        if services_list is not None and services_list != '':
            services_list = services_list.split(',')
            services = Service.objects.filter(id__in=services_list)
            app.services = services
            app.save()
        return JsonResponse({'pet_id': pet.id})
    except IntegrityError as e:
        msg = {'msg': 'Integrity Error'}
        try:
            conflict_email_owner = Customer.objects.get(email=owner_email)
            msg['email_conflict'] = owner_email
            msg['email_conflict_owner'] = conflict_email_owner.name
        except Customer.DoesNotExist:
            pass
        try:
            conflict_phone_owner = Customer.objects.get(cellphone=owner_phone)
            msg['phone_conflict'] = owner_phone
            msg['phone_conflict_owner'] = conflict_phone_owner.name
        except Customer.DoesNotExist:
            pass
        return JsonResponse(msg, status=400)
    except Exception as e:
        return HttpResponse(e.message, status=500)


def create_pet(request):
    try:
        owner_id = request.GET.get('owner_id')
        owner = Customer.objects.get(id=owner_id)
        pet = Pet()
        pet.name = request.GET.get('name')
        breed_id = request.GET.get('breed_id', None)
        if breed_id:

templates/happy/base.html
{% load staticfiles %}
<html lang="en">
<head>
    <link rel="shortcut icon" href="{% static 'happy/img/favicon.jpg' %}">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>HappyDog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="{% static 'happy/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen" />
    <link href="{% static 'happy/css/happy.css' %}" rel="stylesheet" media="screen" />
    <link href="{% static 'happy/fontello/css/fontello.css' %}" rel="stylesheet" media="screen" />
    <script src="{% static 'happy/bootstrap/js/jquery-2.2.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'happy/bootstrap/js/bootstrap.js' %}" type="text/javascript"></script>

    {% block extra_head %}{% endblock %}
</head>
<body>
<div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li id="nav_main"><a href="{% url 'main' %}">Inicio</a></li>
                <li id="nav_customers"><a href="{% url 'customers' %}">Clientes - Peludos</a></li>
                <li id="nav_services"><a href="">Servicios</a></li>
                <li id="nav_products"><a href="">Productos</a></li>
                <li id="nav_bill" class="navbar-right"><a href="">Cobrar</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- Reset active state for navigation -->
<script>
    $( "#nav_main").removeClass();
    $( "#nav_customers").removeClass();
    $( "#nav_services").removeClass();
    $( "#nav_products").removeClass();
</script>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/happy/confirm_delete_appointment.html
<!-- Modal -->
<div class="modal fade" id="confirm_delete_appointment_modal" tabindex="-1" role="dialog" aria-labelledby="confirm_delete_appointment_modal" >
  <div class="modal-dialog" role="document">
    <div class="modal-content alert-danger">
      <div class="modal-header alert-danger">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
          Cancelar Cita
        </h4>
      </div>
      <div class="modal-body alert-danger">
        <div id="modal_content_div">
          Deseas cancelar esta cita?
        </div>
      </div>
      <div class="modal-footer alert-danger">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          Cerrar
        </button>
        <button type="button" class="btn btn-danger" onclick="removeAppointment()">
          <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span> Cancelar Cita
        </button>
      </div>
    </div>
  </div>
</div>

templates/happy/customer_appointments.html
<div class="col-md-12">
  <!-- For each pet and each appointment -->
  <div class="panel-group top-buffer" id="owner_app_accordion" role="tablist" aria-multiselectable="false">
    {% for pet in owner.pet_set.all %}
      {% for app in pet.appointment_set.all %}
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="app_header_{{ owner.id }}_{{ app.id }}" aria-expanded="false" >
            <div class="row">
              <!-- App. Date -->
              <div class="col-md-6">
                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#owner_app_accordion" href="#app_body_{{ owner.id }}_{{ app.id }}" aria-controls="app_body_{{ owner.id }}_{{ app.id }}">
                  {{ app.start | date:"d F - H:i" }}
                </a>
              </div>
              <!-- Pet Name -->
              <div class="col-md-4">
                {{ app.pet.name }}
              </div>
              <div class="col-md-2">
                <a href="{% url 'main' %}#date={{ app.start | date:"Y-m-d" }}#app_id={{ app.id }}"><span class="glyphicon glyphicon-search"></span></a>
              </div>
            </div>
          </div>
          <div id="app_body_{{ owner.id }}_{{ app.id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="app_header_{{ owner.id }}_{{ app.id }}">
            <div class="panel-body">
              {% for service in app.services.all %}
                {{ service.name }} - {{ service.price }}<br>
              {% endfor %}
            </div>
          </div>
        </div>
      {% endfor %}
    {% endfor %}
  </div>
</div>

templates/happy/customers.html
{% extends 'happy/base.html' %}
{% block extra_head %}
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'happy/bootstrap-editable/css/bootstrap-editable.css' %}" type="text/css" media="screen" />
  <script type="text/javascript" src="{% static 'happy/bootstrap-editable/js/bootstrap-editable.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'happy/js/moment.js' %}"></script>
  <script src="{% static 'happy/js/customers.js'  %}" type="text/javascript"></script>
{% endblock %}

{% load happy_filters %}

{% block content %}
  <script>
    $( "#nav_customers").addClass('active');
  </script>
  <div class="row">
    <div class="col-md-4">
      <div class="input-group">
        <input id='' type="text" class="form-control" placeholder="Buscar cliente o peludete...">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
        </span>
      </div>
    </div>
    <div class="col-md-4">
      <div class="input-group">
        <input id='' type="text" class="form-control" placeholder="Raza...">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
        </span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-11">
      <div class="panel-group top-buffer" id="owner_accordion" role="tablist" aria-multiselectable="true">
        <!-- for each customer -->
        {% for owner in customers %}
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="owner_header_{{ owner.id }}" aria-expanded="false" >
              <div class="row">
                <div class="col-md-3">
                  <h4>
                    <a class="collapsed accordion_link" role="button" data-toggle="collapse" data-parent="#owner_accordion" href="#owner_body_{{ owner.id }}" aria-controls="owner_body_{{ owner.id }}">
                      {{ owner.name }}<br>
                      <small>{{ owner.cellphone }}</small>
                    </a>
                  </h4>
                </div>
                {% for pet in owner.pet_set.all %}
                  <div class="col-md-{{ owner.pet_set.count|col_width:'9' }}">
                    <div class="media">
                      <div class="media-left media-middle">
                        <a class="collapsed accordion_link" role="button" data-toggle="collapse" data-parent="#owner_accordion" href="#owner_body_{{ owner.id }}" aria-controls="owner_body_{{ owner.id }}">
                          <img class="media-object pet-image-customer-list img-rounded" src="{% static 'happy/img/tux.jpg' %}" alt="$pet-name">
                        </a>
                      </div>
                      <div class="media-body valign-middle">
                        <h4 class="media-heading">
                          <a class="collapsed accordion_link" role="button" data-toggle="collapse" data-parent="#owner_accordion" href="#owner_body_{{ owner.id }}" aria-controls="owner_body_{{ owner.id }}">
                            {{ pet.name }}<br>
                            <small> {{ pet.breed }}</small><br>
                            <small><a href="{% url 'main' %}#pet={{ pet.id }}" role="button" data-toggle="tooltip" title="Dar cita a {{ pet.name }}"><span class="glyphicon glyphicon-calendar"></span><small> Dar cita</small></a></small>
                          </a>
                        </h4>
                      </div>
                    </div>
                  </div>
                {% endfor %}
              </div>
            </div>
            <div id="owner_body_{{ owner.id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="owner_header_{{ owner.id }}">
              <div class="panel-body">
                <!-- Owner / Pets Info -->
                <div class="row">
                  <!-- Owner Info -->
                  <div class="col-md-4">
                    <form class="form-horizontal form-inline">
                      <div class="form-group">
                        <label class="col-sm-2 control-label"><span class="glyphicon glyphicon-user"></span></label>
                        <div class="col-sm-10">
                          <a href="#" class="xeditable-owner-required" data-type="text" data-pk="{{ owner.id }}" data-url="/update_owner" data-name='name' data-title="Nombre y Appellidos">{{ owner.name }}</a>
                        </div>
                        <label class="col-sm-2 control-label"><span class="glyphicon glyphicon-envelope"></span></label>
                        <div class="col-sm-10">
                          <a href="#" class="xeditable-owner" data-type="text" data-pk="{{ owner.id }}" data-url="/update_owner" data-name='email' data-title="Email">{{ owner.email }}</a>
                        </div>
                        <label class="col-sm-2 control-label"><span class="glyphicon glyphicon-phone"></span></label>
                        <div class="col-sm-10">
                          <a href="#" class="xeditable-owner-required" data-type="text" data-pk="{{ owner.id }}" data-url="/update_owner" data-name='cellphone' data-title="Telefono">{{ owner.cellphone }}</a>
                        </div>
                      </div>
                    </form>
                  </div>
                  <!-- Pets Info -->
                  <div class="col-md-8">
                    <div id="pets">
                      <ul id="pets_tabs" class="nav nav-tabs">
                        {% for pet in owner.pet_set.all %}
                          <li {% if forloop.first %}class="active" {% endif %}><a data-toggle="tab" href="#pet_{{ pet.id }}">{{ pet.name }}</a></li>
                        {% endfor %}
                        <li ><a class="new_pet_tab" data-toggle="tab" href="#new_pet_{{ owner.id }}"><span class="glyphicon glyphicon-plus"> </span> Nuevo Peludo</a></li>
                      </ul>
                      <div class="tab-content border">
                        {% for pet in owner.pet_set.all %}
                          <div id="pet_{{ pet.id }}" class="top-buffer tab-pane fade {% if forloop.first %}in active{% endif %}">
                            <div class="media">
                              <div class="media-left">
                                <img class="img-rounded" src="{% static 'happy/img/tux.jpg' %}" alt="{{ pet.name }}">
                                <h6>
                                  <span class="glyphicon icon-birthday"></span> <a href="#" class="xeditable-pet" data-type="combodate" data-format="DD/MM/YYYY" data-value="{{ pet.birthday | date:"d/m/Y" }}" data-pk="{{ pet.id }}" data-url="/update_pet" data-name='birthday' data-title="Cumpleaños">{% if pet.birthday %}{{ pet.birthday | date:"d F"  }} {% else %} Vacio {% endif %}</a><small>{{ pet.birthday | years_passed}} Años</small><br>
                                  <span class="glyphicon icon-gauge"></span> <a href="#" class="xeditable-pet-size" data-type="select" data-pk="{{ pet.id }}" data-url="/update_pet" data-name='size' data-title="Peso">{{ pet.weight |default_if_none:"0" }}</a><br>
                                  <span class="glyphicon icon-scissors"></span> <a href="#" class="xeditable-pet-hair" data-type="select" data-pk="{{ pet.id }}" data-url="/update_pet" data-name='hair_type' data-title="Pelo">{{ pet.hair_type |default_if_none:"Vacio" }}</a>
                                </h6>
                              </div>
                              <div class="media-body">
                                <h4 class="media-heading">
                                  <a href="#" class="xeditable-pet-required" data-type="text" data-pk="{{ pet.id }}" data-url="/update_pet" data-name='name' data-title="Nombre">{{ pet.name }}</a>
                                  <small> <a href="#" class="xeditable-pet-breed" data-type="select" data-pk="{{ pet.id }}" data-url="/update_pet" data-name='breed' data-title="Raza">{{ pet.breed|default_if_none:"Vacio" }}</a></small>
                                </h4>
                                <a href="#" class="xeditable-pet" data-type="text" data-pk="{{ pet.id }}" data-url="/update_pet" data-name='annotations' data-title="Descripcion">{{ pet.annotations|default_if_none:"Vacio" }}</a>
                                <p></p>
                              </div>
                            </div>
                          </div>
                        {% endfor %}
                        {% include 'happy/new_pet_tab.html' %}
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Carrousel -->
                <div class="row">
                  {% include 'happy/carrousel.html' %}
                </div>
                <!-- Appointments -->
                <div class="row">
                  {% include 'happy/customer_appointments.html' %}
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

templates/happy/main.html
{% extends 'happy/base.html' %}
{% block extra_head %}
  {% load staticfiles %}
  <link href="{% static 'happy/fullcalendar/fullcalendar.css' %}" rel='stylesheet' media="screen" />
  <link href="{% static 'happy/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}" rel="stylesheet" media="screen" />
  <script src="{% static 'happy/js/moment.js' %}" type='text/javascript' ></script>
  <script src="{% static 'happy/fullcalendar/fullcalendar.min.js' %}" type='text/javascript'></script>
  <script src="{% static 'happy/fullcalendar/lang/es.js' %}" type='text/javascript'></script>
  <script src="{% static 'happy/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}" type='text/javascript'></script>
  <script src="{% static 'happy/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js' %}" type='text/javascript'></script>
  <script src="{% static 'happy/js/main.js' %}" type="text/javascript"></script>
  <script src="{% static 'happy/js/typeahead-bundle.js' %}" type='text/javascript'></script>
  <script src="{% static 'happy/js/handlebars.js' %}" type='text/javascript'></script>
{% endblock %}

{% block content %}
<script>
    $( "#nav_main").addClass('active');
</script>
<div class="row">
  <div id='calendar' class="col-lg-8">
  </div>
  <div class="col-sm-4">
    {% include 'happy/search_pet.html' %}
  </div>
</div>
{% include 'happy/pet_appointment.html' %}
{% include 'happy/pet_birthdays.html' %}
{% include 'happy/confirm_delete_appointment.html' %}
{%  include 'happy/pay_appointment.html' %}
{% endblock %}